### ISSUE TITLE
.desc files to describe volumes to load

### ISSUE THREAD

**Issue by kmilo9999** [ridatadiscoverycenter/react-aframe-volume-renderer#14]
season_tide_variable_X_X_X_X.png
wont work the current way the filename is being parsed. I was thinking on creating a *.desc file (i.e season_tide_year.desc ) where the size of the volume and path of the of the png is stored and then send that data to the shader

**Comment by mcmcgrath13** [comment]
Are `.desc` files an easy standard?  It might be easier to use `.json` since those are trivial to load/parse into the web app
