### ISSUE TITLE
data: get pngs

### ISSUE THREAD

**Issue by mirestrepo** [ridatadiscoverycenter/react-aframe-volume-renderer#2]
There will be 8 volumes, 4 for salinity, 4 for temperature. low tide, high tide for summer and winter.

- [ ] Delete nrrds
- [x] Extract Data 
- [ ] Merge PR with data 

Jan 15, Jul 15

**Comment by eldu** [comment]
[Notion](https://www.notion.so/brownccv/RIDDC-Notes-157e92ee79994083ab8d153fd4b74999)

[Diagram](https://drive.google.com/file/d/1-aZnWQrg01eHw_2pyzNEmcWGWDazbSxC/view)

**Comment by eldu** [comment]
Repo for the data scripts - https://github.com/brown-ccv/matlab_nc_converter

**Comment by eldu** [comment]
Name the files with salinity/temp, low/high tide, and winter/summer.

**Comment by eldu** [comment]
File Format name

`season_tide_variable.nrrd`

season is winter/summer
tide is low/high
variable is salt/temp

ex/ 
`summer_low_salt.nrrd`

**Comment by kmilo9999** [comment]
We dont actually need nrrds. We need the raw files given by the matlab script, convert them to tiff image series and then transforming them to 2D pngs. The current pipeline needs to be scripted (and improved). At this moment I am converting raw to tiff series using FIJI.
