### ISSUE TITLE
Add padding to Howto Modal

### ISSUE THREAD

**Issue by RobertGemmaJr** [ridatadiscoverycenter/react-aframe-volume-renderer#27]
Text and images run right to the edge of the `<Modal>` in `Howto.js`. Add a little padding along the x axis to space things out

![image](https://user-images.githubusercontent.com/38439940/134420313-824ad562-2473-4805-a582-affddc9c11a4.png)

**Comment by kmilo9999** [comment]
Was this issue closed with #50 ?
