### ISSUE TITLE
feat: change data radio buttons

### ISSUE THREAD

**Issue by mirestrepo** [ridatadiscoverycenter/react-aframe-volume-renderer#3]
Three groups: season. low/high tide, and variable (salinity/temp)

**Comment by mirestrepo** [comment]
Start UI - and do state via Context

**Comment by RobertGemmaJr** [comment]
Radio Buttons: summer/winter and low/high tide

Channel Selector: All, Salinity, Temperature
Use appropriate [color scheme ](https://www.mathworks.com/matlabcentral/fileexchange/57773-cmocean-perceptually-uniform-colormaps) - `haline` for salinity and `thermal` for temperature
