### ISSUE TITLE
Remove FireBase dependency

### ISSUE THREAD

**Issue by kmilo9999** [ridatadiscoverycenter/react-aframe-volume-renderer#69]
If we are only using Firebase a hosting, you dont need it as a dep.

**Comment by RobertGemmaJr** [comment]
Do you mean it only has to be a dev dependency?  @kmilo9999

**Comment by kmilo9999** [comment]
We dont need it all.

**Comment by RobertGemmaJr** [comment]
It gives me errors when I remove `firebase` and `firebase-tools`, @mcmcgrath13 can you confirm? Can I make `firebase` a dev dependency or should I just leave it?

**Comment by mcmcgrath13** [comment]
What's the error?

We shouldn't need `firebase` at all - we still might need `firebase-tools`
